language: c

compiler: 
    - gcc

arch: arm64

os:
    - linux

cache:
  directories:
    - dpdk-dir

addons:
  apt:
    packages:
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - python3-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunwind-dev
      - python-dev
      - python-pip
      - python-setuptools
      - python3-dev
      - python3-setuptools
      - python3-pip
      - libtool

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
   - DISABLE_SPARSE=1 DPDK=1 OPTS="--enable-shared"
   - DISABLE_SPARSE=1 DPDK_SHARED=1 OPTS="--enable-shared"
   - DISABLE_SPARSE=1 TESTSUITE=1 DPDK=1
   - DISABLE_SPARSE=1 OPTS="--disable-ssl"
   
matrix:
    include:
      - os: osx
        compiler: clang
        env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - lance.yang@arm.com
