language: c
compiler:
  - gcc

os:
  - linux

cache:
  directories:
    - dpdk-dir

addons:
  apt:
    packages:
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - python3-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunwind-dev
      - python-pip
	  - python-setuptools

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

matrix:
  include:
    - os: linux
      arch: arm64
      compiler: gcc
      env: KERNEL_LIST="5.0 4.20 4.19 4.18 4.17 4.16"
    - os: linux
      arch: arm64
      compiler: gcc
      env: KERNEL_LIST="4.15 4.14 4.9  4.4  3.19 3.16"
    - os: linux
      arch: arm64
      compiler: gcc
      env: OPTS="--disable-ssl"
    - os: osx
      compiler: clang
      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - lance.yang@arm.com
